# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containerNumber', models.CharField(default='', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNumber', models.CharField(max_length=20)),
                ('quantitySkids', models.IntegerField()),
                ('pcsPerSkid', models.IntegerField()),
                ('containerNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Container')),
            ],
        ),
        migrations.AddField(
            model_name='incoming',
            name='containerNumber',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Container'),
            preserve_default=False,
        ),
    ]
